spring.application.name=eurekaserver

# Server Port
server.port=8761

# Eureka Instance Configuration
eureka.instance.hostname=localhost

# Disable self-registration since this is a standalone registry
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Eureka Dashboard and Service URL
eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka/