# --- APPLICATION-DOCKER.PROPERTIES ---
spring.application.name=productservice
server.port=8082

# Point to the internal Docker container names
spring.datasource.url=jdbc:mysql://mysql-server:3306/product_db_aerocarry?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

# Point to internal Docker container
spring.kafka.bootstrap-servers=kafka:9092

# Point to internal Docker container
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/