# --- APPLICATION-LOCAL.PROPERTIES ---
spring.application.name=productservice
server.port=8082

# Point to your EC2 Public IP
spring.datasource.url=jdbc:mysql://3.110.225.113:3306/product_db_aerocarry?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

# Point to EC2 Public IP
spring.kafka.bootstrap-servers=3.110.225.113:9092

# Point to EC2 Public IP
eureka.client.service-url.defaultZone=http://3.110.225.113:8761/eureka/