# --- APPLICATION-LOCAL.PROPERTIES ---
spring.application.name=productservice
server.port=8082

# Point to your EC2 Public IP
spring.datasource.url=jdbc:mysql://43.205.232.191:3306/product_db_aerocarry?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

# Point to EC2 Public IP
spring.kafka.bootstrap-servers=43.205.232.191:9092

# Point to EC2 Public IP
eureka.client.service-url.defaultZone=http://43.205.232.191:8761/eureka/