spring.application.name=payment-service
# Server
server.port=8084

# Database
spring.datasource.url=jdbc:mysql://mysql-server:3306/payment_db_aerocarry?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Vippul36@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

# Eureka
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

# Kafka Consumer Configuration
spring.kafka.consumer.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=payment-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# We will also add Razorpay/Stripe API keys here later