spring.application.name=order-service

# Server
server.port=8083

# Database
spring.datasource.url=jdbc:mysql://mysql-server:3306/order_db_aerocarry?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

# Eureka Client
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

# Kafka Producer Configuration
spring.kafka.producer.bootstrap-servers=kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer